import Link from "next/link";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navigation = [
    { href: "/", label: "Home" },
    { href: "/signup", label: "Sign Up" },
    { href: "/login", label: "Log In" },
    { href: "/dashboard", label: "Dashboard" },
    { href: "/account", label: "My Account" },
    { href: "/newtaskboard", label: "New Taskboard" },
    { href: "/taskboard", label: "Taskboard" },
  ];

  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <ul>
              {navigation.map((navitem) => (
                <li key={navitem.href}>
                  <Link href={navitem.href}>{navitem.label}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
